### ISSUE TITLE
Stationary  Thunderbird 60* compatibilty

### ISSUE THREAD

**Issue by blackcrack** [arivald/tbirdExt#3]
Hi,

also at TB 60* ?

best regards
Blacky

and thank you, very nice addon !

**Comment by arivald** [comment]
Well, it is ready, (https://github.com/arivald/tbirdExt/blob/master/xpi%20archive/stationery-1.0.0.xpi).
I sent it for review long ago, but TB team apparently can't finish the review for some reason.
Anyway, most probably I will not do any new version, because all existing API will be dropped, and only limited WebExtension API will remain...

**Comment by blackcrack** [comment]
pity ... :\ maybe will in future again different api's add again \*pray*
the TB was so cool with the whole plugin possibility's ..

best regards
Blacky

**Comment by RealRaven2000** [comment]
Arivald - I would have reviewed it ages ago but you attached some sources so that it was automatically Admin flagged. Our only Admin reviewer is is currently on paid leave., I will ask him again to review it when he is back.

**Comment by tmetro** [comment]
RealRaven2000 wrote:
>would have reviewed it ages ago but you attached some sources

Worth resubmitting without the files that triggered the admin review?

arivald wrote:
>Well, it is ready,

You posted a download link to some file sharing site in response to a review. That link has expired. I recommend you post a link to the XPI here either in response to a review or as part of the add-on description.

In general, the add-on description at addons.thunderbird.net should include links here for filing bugs, etc.

>all existing API will be dropped

I thought that transition happened around version 58. If your add-on works with 60, doesn't that imply it has been updated to the new APIs? (Or are the version numbers for the API transition different for TB than Firefox?)

**Comment by blackcrack** [comment]
an answer could be interesting @arivald

**Comment by arivald** [comment]
> Worth resubmitting without the files that triggered the admin review?

Well, the mentioned library is and Ace editor (for HTML source), well known open source project. https://ace.c9.io/
There is a little path, executed automatically during build, last time it was reviewed fine, and it was not changed since then.

> I recommend you post a link to the XPI [...] as part of the add-on description.

I'm afraid I have to do this.

> I thought that transition happened around version 58. If your add-on works with 60, doesn't that imply it has been updated to the new APIs? (Or are the version numbers for the API transition different for TB than Firefox?)

You wish :-). Tb 60 is a compromise, they adapted to changes in Gecko, they leave support for overlays for sake of compatibility. After that, even TB devs do not know... see https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_63, they wrote:
> The picture beyond Thunderbird version 60 is rather uncertain, given the continued high rate of change in Firefox platform code.
